# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tenderloin}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mitchell Hashimoto", "John Bender", "Lincoln Stoll"]
  s.date = %q{2012-08-30}
  s.description = %q{Tenderloin is a tool for building and distributing virtualized development environments using VMWare fusion.}
  s.email = ["mitchell.hashimoto@gmail.com", "john.m.bender@gmail.com", "lstoll@me.com"]
  s.executables = ["loin"]
  s.extra_rdoc_files = [
    "LICENCE",
     "README.md"
  ]
  s.files = %w[lib bin script templates config].map {|d| Dir.glob("#{d}/**/*")}.flatten + %w[LICENCE README.md Version]
  s.homepage = %q{http://github.com/lstoll/tenderloin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Tenderloin is a tool for building and distributing virtualized development environments using VMWare fusion.}
  s.test_files = Dir.glob("test/**/*")

  s.add_runtime_dependency "net-ssh",               ">= 2.0.19"
  s.add_runtime_dependency "net-scp",               ">= 1.0.2"
  s.add_runtime_dependency "json",                  ">= 1.2.0"
  s.add_runtime_dependency "archive-tar-minitar",   "= 0.5.2"
  s.add_runtime_dependency "thor"
end
